statsbombpy/sb.py, tests/statsbombpy_test/test_sb.py
I've noticed that the 2003/04 PL matches file ([data/matches/2/44.json](https://github.com/statsbomb/open-data/blob/master/data/matches/2/44.json)) in statsbomb-opendata has no data for stadiums, which causes this program to raise a KeyError exception when downloading the matches file. I've raised the data collection issue on the opendata repository, but given that its such a minor part of the matches file, I've added a check to allow for the system to return the dataframe sans the stadium column if it doesn't exist.
=> add a check to see if competition_stage, stadium, and referee columns exist in matches dataframe.

setup.py, statsbombpy/helpers.py
Executing `import sb from statsbompy` would result in an error using Python 3.7 and up, as `dummy_thread` which is used by `cashier` has been deprecated. Fortunately, `functools.lru_cache` (included since Python 3.2) provides the same functionality as the `@cache` decorator from cashier and allows us to avoid using cashier altogether.
=> Removed cashier cache in favor of functools.lru_cache

statsbombpy/sb.py, tests/statsbombpy_test/test_sb.py
Fixed bug in `competition_events`. 
`competitions` and `matches` were being called with creds was being passed as a positional argument in the wrong position, and output from these was assumed to be a dict, but dataframes were being returned. The function calls to `competitions` and `matches` within `competition_events` have been fixed to explicitly ask the returned objects to be dicts (using the `fmt` argument) and are now passing creds as a kwarg.
=> Competition events fix

README.md, setup.py, statsbombpy/api_client.py, statsbombpy/config.py, statsbombpy/entities.py, statsbombpy/helpers.py, statsbombpy/public.py, statsbombpy/sb.py, tests/statsbombpy_test/test_sb.py
`sb.frames` returns the json as-is from the API, or a dataframe with columns `event_uuid`, `visible_area` (list of vertices), `freeze_frame` (dict).
`sb.competition_frames` pulls all 360 frames for a comp and returns either a list of dicts (one per match) or a dataframe with all FFs.
if the wrong creds are supplied `frames` returns an empty dict/dataframe with a warning.
mirrored the tests for other functions and applied black formatting/removed some unused imports/generally cleaned up some stuff too.
=> utilities to pull 360 frames from the API

statsbombpy/helpers.py
`sb.events()` and therefore `sb.competition_events()` return event data with no player ids as pointed out by a support query.
Upon inspection, we appear to remove all ids relating to event tags. A simple fix would be to add them all but that results in ~35 extra columns.
Instead, this PR only adds the id if it's for the player or the possession team hence the resulting table has team and player ids.
=> Add player and team ids to events function

tests/statsbombpy_test/test_sb.py
The test for the `sb.frames()` function is wrong. This fixes it.
=> Fix frames test to work with modified frames function

README.md, setup.py, statsbombpy/api_client.py, statsbombpy/config.py, statsbombpy/entities.py, statsbombpy/public.py, statsbombpy/sb.py, tests/statsbombpy_test/test_sb.py
Summary of changes:
- Change `README` to reflect that we have open 360 data now.
- Bump version number.
- Add path to the JSON files in `OPEN_DATA_PATHS`.
- Add a function to `entities` which adds the match_id to the resulting 360 data, this is something the current frames function was missing. 
- Remove the exception stating there was no open 360 data. 
- Update the tests to reflect the changes made above and also change the `competition_frames()` test to use a smaller competition.
=> Add free 360 functionality

README.md, setup.py, statsbombpy/sb.py, tests/statsbombpy_test/test_sb.py
When `matches` function in `sb.py` returns a Pandas dataframe, it now includes the `home_managers` and `away_managers` as a `str` of names. Applied black formatting as well to tidy up some of the code.
Added tests for the manager parsing in `test_sb.py`, including a case where multiple managers are present.
Added managers to the `sb.matches` example in  `README.md`.
=> Add home and away managers to match dataframe output

setup.py, statsbombpy/api_client.py, statsbombpy/entities.py, statsbombpy/helpers.py, statsbombpy/public.py, statsbombpy/sb.py, tests/statsbombpy_test/test_sb.py
There are a number of match ids that, when passed to the `sb.lineups` function, throw an error. This is caused by one of the players in the lineup not having country information.
This fix checks whether or not we have the player's country and assigns it as 'Unknown' if we do not.
=> Fix lineups function handle missing player countries

statsbombpy/api_client.py, statsbombpy/errors.py
When running code without credentials, the 'credentials not supplied' message
was printed to the console on each function invocation, which is very annoying
when loading a batch of data. This commit replaces the print message by a custom
``NoAuthWarning`` which the user can filter easily.
See also #2 and #21.
=> Replace "credentials were not supplied" print message by warning

setup.py, statsbombpy/entities.py, tests/statsbombpy_test/test_sb.py
It's been pointed out that the `sb.matches()` function only returns the games we have already collected for the competition season even though the API returns all the matches for the comp-season regardless of whether they have been collected or not. 
StatsBombR also returns all matches so better to have the two aligned.
I also removed the matches test for dual managers as the particular instance has been fixed in the raw data so that test fails now.
=> Change matches function to include all games for a competition season

setup.py, statsbombpy/sb.py, tests/statsbombpy_test/test_sb.py
- Some open data is missing visible area coordinates for its 360 frames.
- If you pull the 360 data for one of those matches using the `sb.frames()` function it returns an error:
`ValueError: operands could not be broadcast together with shape (0,) (1307,)`
- Here we modify the `sb.frames()` function so that you can still get the 360 data for open data matches that are missing visible area data.
- I also added a test to check one of the culprit matches.
=> Fix visible-area bug

README.md, setup.py, statsbombpy/api_client.py, statsbombpy/config.py, statsbombpy/entities.py, statsbombpy/helpers.py, statsbombpy/sb.py, tests/statsbombpy_test/test_sb.py
An update to expose the new SB360 metrics
Key changes:
- Bumped up minor version of this project
- `events` now accepts an optional `include_360_metrics` argument to merge-in 360 metrics for matches where 360 data is available
- `frames`, a function that fetches the 360 frames now has player-level metrics i.e. distance of each player from the visible area edge exposed
- `competition_events(include_360_metrics=True)` and `competition_frames` have also been updated to work as expected
- `competition_frames` has been changed to unpack the freeze_frames, to be more consistent with the output of `frames`
Developer notes: 
The merging of events and frames when you call events with `include_360_metrics=True` is now happening at the native dict-level before the dataframes get created, so you …
=> Expose 360 metrics

README.md, setup.py, statsbombpy/sb.py
360 metrics are not available in open data. 
Key changes:
- Raise exception when attempting to retrieve 360 metrics on open data
- Updated README to specify that open data does not include 360 metrics
- Bumped up patch version number
=> Raise exception when using 360_metrics with open_data

setup.py, statsbombpy/helpers.py
When the user sets `include_360_metrics=True` in the `sb.events()` function we drop the `match_id`.
=> Fix missing match_id bug

setup.py, statsbombpy/helpers.py
We are dropping the `team_id` variable when using the `sb.events()` function.
=> Fix missing team_id bug

README.md, setup.py, statsbombpy/config.py, statsbombpy/sb.py
- Instead of hard-coding the number of cores to use we now let the user set the number as an env var, failing that we try to detect them and failing that we hard-code it as 4 as we have done previously.
=> Allow configurable concurrency

setup.py, statsbombpy/config.py
We have released version 4.0 for both the player-match-stats API and the player-season-stats API. This change updates those numbers in statsbombpy.
=> Bump player season, match and event api version number

setup.py, statsbombpy/config.py
We have released v6 of the 'matches in competition' API - this change bumps the version number in statsbombpy so that it hits the new version.
=> Bump matches api version number

setup.py, statsbombpy/helpers.py
We're currently dropping the pass recipient id column when the events are pulled and this change fixes that.
=> Fix missing pass receipt id column

setup.py, statsbombpy/sb.py
- Currently there are some matches with frames that have the variable `distances_from_edge_of_visible_area` set to `None`.
- This causes an error when returning the frames for that match. 
- This variable should never be `None` per the data spec, however this is unlikely to be fixed in the raw data any time soon. 
- As such, we have updated the `frames()` function to handle these cases.
- We'll remove this functionality when the raw data gets fixed.
=> Add exception for none type frames
